"""
cloud/markdown_export.py — Markdown export for context blocks and event windows.

The user-facing export (spec §6) is Markdown, even though the internal
LLM request uses TOON. This makes context usable with ChatGPT, Claude,
IDEs, and documentation workflows without requiring a ContextClip client.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import List, Optional

from core.contracts import ContextBlock, Event, EventType


APP_ICON = {
    "vs_code": "💻",
    "browser_chrome": "🌐",
    "browser_edge": "🌐",
    "browser_firefox": "🌐",
    "word": "📝",
    "powerpoint": "📊",
    "excel": "📊",
    "outlook": "📧",
    "teams": "💬",
    "terminal": "⬛",
    "slack": "💬",
    "unknown": "🖥️",
}


def _icon(app_family: str) -> str:
    return APP_ICON.get(app_family, "🖥️")


def _fmt_time(ts: str) -> str:
    try:
        dt = datetime.fromisoformat(ts.replace("Z", "+00:00"))
        return dt.strftime("%Y-%m-%d %H:%M UTC")
    except Exception:
        return ts


def export_events_markdown(events: List[Event], block: Optional[ContextBlock] = None) -> str:
    """
    Export a list of events as a user-copyable Markdown context block.
    Implements the contract from spec §6.
    """
    lines = []

    if block:
        lines.append(f"## ContextClip Context Block {block.id}")
        lines.append(f"**Workflow:** {block.workflow_id}")
        events_range = f"{block.event_start}–{block.event_end}"
        lines.append(f"**Events:** {events_range}")
    else:
        lines.append("## ContextClip Active Context")

    if events:
        app_flow = []
        seen = set()
        for e in events:
            fam = e.source_app.app_family
            if fam not in seen:
                app_flow.append(f"{_icon(fam)} {fam}")
                seen.add(fam)
        lines.append(f"**Apps:** {' → '.join(app_flow)}")

    lines.append("")

    if block:
        lines.append("### Goal")
        lines.append(block.one_line_goal)
        lines.append("")

    lines.append("### Timeline")
    for i, e in enumerate(events, 1):
        icon = _icon(e.source_app.app_family)
        verb = "Copy" if e.type == EventType.COPY else "Paste"
        dest_str = ""
        if e.destination_app:
            dest_icon = _icon(e.destination_app.app_family)
            dest_str = f" → {dest_icon} {e.destination_app.app_family}"
        time_str = _fmt_time(e.timestamp_utc)
        preview = e.clipboard.preview_text[:120]
        lines.append(f"{i}. **{verb}** | {icon} {e.source_app.app_family}{dest_str} | `{time_str}`")
        lines.append(f"   > {preview}")
        if e.screenshot_id:
            lines.append(f"   [screenshot](contextclip://screenshot/{e.screenshot_id})")
        lines.append("")

    if block and block.important_entities:
        lines.append("### Key Entities")
        for entity in block.important_entities:
            lines.append(f"- `{entity}`")
        lines.append("")

    if block and block.open_questions:
        lines.append("### Open Questions")
        for q in block.open_questions:
            lines.append(f"- {q}")
        lines.append("")

    if block and block.narrative:
        lines.append("### Summary")
        lines.append(block.narrative)
        lines.append("")

    if block and block.toon_payload:
        lines.append("### TOON Payload (for LLM)")
        lines.append("```toon")
        lines.append(block.toon_payload)
        lines.append("```")
        lines.append("")

    lines.append("---")
    lines.append(f"*Generated by ContextClip at {_fmt_time(datetime.now(timezone.utc).isoformat())}*")

    return "\n".join(lines)


def export_workflow_markdown(blocks: List[ContextBlock], events_by_block: dict) -> str:
    """Merge multiple context blocks into a single Markdown document."""
    lines = ["# ContextClip Workflow Export", ""]
    for block in blocks:
        events = events_by_block.get(block.id, [])
        lines.append(export_events_markdown(events, block))
        lines.append("")
        lines.append("---")
        lines.append("")
    return "\n".join(lines)
